Repository Letifery/income-analysis-USA, pull requests merged in 2021-12, with the labels that each got.

#4 Added file for exploritory-data-analysis and changed file structure
  utils/evaluation-measures.py
  utils/exploritory-data-analysis.py
Labels: enhancement

#5 Added stratified-kfold cross evaluation
  main.py
  utils/exploritory-data-analysis.py
  utils/strat-kfold.py
Labels: documentation, enhancement

#6 Added plotting function, documentation...
  utils/model-alteration.py
Labels: documentation, enhancement

#7 Changed plotting and added several functions
  utils/model-alteration.py
Labels: documentation, enhancement

#8 Update model-alteration.py
  utils/model-alteration.py
Labels: enhancement

#9 Update main.py
  main.py
Labels: enhancement

#10 v0.7.0
  utils/data-visualization.py
  utils/evaluation-measures.py
  utils/model-alteration.py
Labels: bug, documentation, enhancement

#11 Update model-alteration.py
  utils/model-alteration.py
Labels: bug, documentation, enhancement

#12 Update data-visualization.py
  utils/data-visualization.py
Labels: documentation, enhancement

#13 Update exploritory-data-analysis.py
  utils/exploritory-data-analysis.py
Labels: enhancement

#14 Update model-alteration.py
  utils/model-alteration.py
Labels: documentation

#15 Create data-preparation.py
  utils/data-preparation.py
Labels: documentation, enhancement

#18 Update README.md
  README.md
Labels: documentation

#20 Fixed issue #19
  utils/model-alteration.py
Labels: small bug

#24 Replaced by the .ipynb variant #23
  main.py
Labels: duplicate

#23 initial commit
  income-analysis-USA.ipynb
Labels: enhancement
